### ISSUE TITLE
Support for aarch64

### ISSUE THREAD

**Issue by tsawada** [d-asnaghi/bazel-arm-none-eabi#2]
Hi. Thanks for sharing your toolchain!

Do you think supporting aarch64 could be a part of the scope of this toolchain? ARM also distributes toolchains for Aarch32/Aarch64.

https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads

Thanks!

**Comment by d-asnaghi** [comment]
Hi @tsawada, I think that the link you sent me is not for `arm-none-eabi` but this [link](gcc-arm-none-eabi-9-2020-q2-update-aarch64-linux.tar.bz2) should be the right one for aarch64.

I'll work on adding it to the toolchain this weekend

**Comment by tsawada** [comment]
Thank you for your quick response!
Actually I wanted to ask if adding toolchain for target `aarch64-none-elf` in this repository makes sense, rather than adding `arm-none-eabi` toolchains for host=aarch64. Now I'm guessing the answer is it'd make more sense to have a separate repository for `aarch64-none-elf`.

**Comment by d-asnaghi** [comment]
I agree with your statement, these are fundamentally two different toolchains, so they should probably be treated separately and have different repositories. Feel free to use this project as a template if you think it might be useful. 

I am planning on adding a RISC-V gcc repo which would probably be quite similar

**Comment by tsawada** [comment]
Thanks! I'll look into it.

**Comment by d-asnaghi** [comment]
I just finished adding support for `aarch64` hosts to this toolchian, if you don't mind reviewing this PR I'll merge it and close this issue. 

I know it does not fully address your issue, but it's a nice addition to this project. Thanks for pointing this out
